### ISSUE TITLE
Packages not sent

### ISSUE THREAD

**Issue by leisipeisi** [hatching/httpreplay#16]
Hi,

I am trying to use your tool, but I am facing some difficulties. I have a pcap file containing the whole communication between my kali linux and a webserver, where kali linux sends packages from different ports to the webserver and the webserver responds with content or some HTTP error codes. 
When I am strarting httpreplay with this pcap file, I get an output of all HTTP requests in the pcap file (seems to be everything okay), in addition I see some warnings that there are unknown streams. When I look at wireshark or tcp dump I don't see that any packages are sent. Am I missing some essential point or am I missinterpreting the purpose of the code? May the unknown streams be an issue? 

Thanks for any help!

**Comment by jbremer** [comment]
Hi, without your PCAPs there's not much I can do to help you ;-) If you can share those, let me know.
